theme: jekyll-theme-minimal
title: Taste Shahi homepage
description: Bookmark this to keep an eye on my project updates!
title: "Taste Shahi"
description: "Delicious recipes and cooking tips"
baseurl: ""    # If it's user site; for project site, put /repo-name
# url: "https://swad-rajsi.github.io"

theme: minima   # or choose another, or use `remote_theme`

# Recipe-specific settings (optional)
collections:
  recipes:
    output: true
    permalink: /recipes/:name/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Author / social (optional)
author:
  name: "Ms Sahi"
  email: "you@example.com"
